import { useEffect, useState } from 'react'
import { Check, Copy, ImagePlus, Trash2, Upload } from 'lucide-react'
import { can, formatPanelDate, PANEL_PERMISSIONS, requestJson, type SessionUser } from './shared'

interface MediaFile { name: string; url: string; size: number; updatedAt: string }
function formatSize(bytes: number) { return bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB` }

export function MediaManager({ user }: { user: SessionUser }) {
  const [files, setFiles] = useState<MediaFile[]>([])
  const [uploading, setUploading] = useState(false)
  const [copied, setCopied] = useState('')
  const [error, setError] = useState('')
  const mayManage = can(user, PANEL_PERMISSIONS.mediaManage)
  async function load() { try { const data = await requestJson('/api/admin/uploads'); setFiles(data.files) } catch (err) { setError(err instanceof Error ? err.message : 'No pudimos cargar los medios.') } }
  useEffect(() => { load() }, [])
  async function upload(file?: File) { if (!file) return; setUploading(true); const form = new FormData(); form.append('file', file); try { await requestJson('/api/admin/uploads', { method: 'POST', body: form }); await load() } catch (err) { setError(err instanceof Error ? err.message : 'No pudimos subir la imagen.') } finally { setUploading(false) } }
  async function copy(url: string) { await navigator.clipboard.writeText(`${window.location.origin}${url}`); setCopied(url); window.setTimeout(() => setCopied(''), 1800) }
  async function remove(file: MediaFile) { if (!window.confirm('¿Eliminar esta imagen de la biblioteca? Verifica que ninguna entrada la esté usando.')) return; try { await requestJson(`/api/admin/uploads/${encodeURIComponent(file.name)}`, { method: 'DELETE' }); await load() } catch (err) { setError(err instanceof Error ? err.message : 'No pudimos eliminar la imagen.') } }
  return <div className="flex flex-col gap-6"><section className="flex flex-col justify-between gap-4 rounded-3xl border border-white/10 bg-ink-800 p-6 sm:flex-row sm:items-center"><div><h2 className="text-lg font-bold">Biblioteca de medios</h2><p className="mt-1 text-sm text-white/45">Imágenes disponibles para entradas y páginas.</p></div>{mayManage && <label className="inline-flex cursor-pointer items-center justify-center rounded-full bg-brand px-5 py-3 text-sm font-bold text-ink"><Upload className="mr-2 size-4" />{uploading ? 'Subiendo...' : 'Añadir imagen'}<input type="file" className="sr-only" accept="image/jpeg,image/png,image/webp,image/gif" disabled={uploading} onChange={(e) => upload(e.target.files?.[0])} /></label>}</section>{error && <p className="rounded-xl bg-red-400/10 p-3 text-sm text-red-300">{error}</p>}<section className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{files.map((file) => <article key={file.name} className="group overflow-hidden rounded-3xl border border-white/10 bg-ink-800"><div className="aspect-square overflow-hidden bg-black/20"><img src={file.url} alt="" className="size-full object-cover transition duration-500 group-hover:scale-105" /></div><div className="p-4"><p className="truncate text-xs font-semibold" title={file.name}>{file.name}</p><p className="mt-1 text-[11px] text-white/35">{formatSize(file.size)} · {formatPanelDate(file.updatedAt)}</p><div className="mt-4 flex gap-2"><button onClick={() => copy(file.url)} className="inline-flex flex-1 items-center justify-center rounded-xl border border-white/10 px-3 py-2 text-xs font-semibold hover:border-brand/40">{copied === file.url ? <Check className="mr-1.5 size-3.5 text-emerald-300" /> : <Copy className="mr-1.5 size-3.5" />}{copied === file.url ? 'Copiada' : 'Copiar URL'}</button>{mayManage && <button onClick={() => remove(file)} className="rounded-xl border border-white/10 p-2 text-white/40 hover:text-red-300" aria-label="Eliminar imagen"><Trash2 className="size-4" /></button>}</div></div></article>)}{files.length === 0 && <div className="col-span-full flex min-h-64 flex-col items-center justify-center rounded-3xl border border-dashed border-white/15 text-center"><ImagePlus className="mb-4 size-10 text-white/20" /><p className="text-sm text-white/45">La biblioteca está vacía.</p></div>}</section></div>
}
