import { useEffect, useState, type FormEvent } from 'react'
import { BarChart3, CheckCircle2, Save, ShieldCheck } from 'lucide-react'
import { fieldClass } from '../ui/FormField'
import { requestJson } from './shared'

interface Settings { metaPixelId: string; googleGtagId: string; clientifySiteId: string }

export function TrackingSettings() {
  const [settings, setSettings] = useState<Settings>({ metaPixelId: '', googleGtagId: '', clientifySiteId: '' })
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  useEffect(() => { requestJson('/api/admin/settings').then((data) => setSettings({ metaPixelId: data.settings.metaPixelId || '', googleGtagId: data.settings.googleGtagId || '', clientifySiteId: data.settings.clientifySiteId || '' })).catch((err) => setError(err instanceof Error ? err.message : 'No pudimos cargar la configuración.')) }, [])
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setError(''); setMessage(''); try { const data = await requestJson('/api/admin/settings', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(settings) }); setSettings({ metaPixelId: data.settings.metaPixelId || '', googleGtagId: data.settings.googleGtagId || '', clientifySiteId: data.settings.clientifySiteId || '' }); setMessage('Configuración guardada. Los cambios se aplicarán a las páginas públicas.') } catch (err) { setError(err instanceof Error ? err.message : 'No pudimos guardar la configuración.') } finally { setSaving(false) } }
  return <form onSubmit={save} className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]"><section className="flex flex-col gap-6 rounded-3xl border border-white/10 bg-ink-800 p-6 sm:p-8"><div><h2 className="text-lg font-bold">Píxeles y analítica</h2><p className="mt-2 text-sm leading-relaxed text-white/50">Configura los identificadores usados para medir campañas y visitas. No pegues scripts completos; solo el ID.</p></div>{error && <p className="rounded-xl bg-red-400/10 p-3 text-sm text-red-300">{error}</p>}{message && <p className="rounded-xl bg-emerald-400/10 p-3 text-sm text-emerald-300">{message}</p>}
    <label className="flex flex-col gap-2 text-sm font-semibold">Meta Pixel ID<input value={settings.metaPixelId} onChange={(e) => setSettings({ ...settings, metaPixelId: e.target.value })} className={fieldClass} placeholder="123456789012345" /><span className="text-xs font-normal text-white/40">Identificador numérico disponible en el Administrador de eventos de Meta.</span></label>
    <label className="flex flex-col gap-2 text-sm font-semibold">Google tag / Google Pixel<input value={settings.googleGtagId} onChange={(e) => setSettings({ ...settings, googleGtagId: e.target.value.toUpperCase() })} className={fieldClass} placeholder="G-XXXXXXXXXX" /><span className="text-xs font-normal text-white/40">Compatible con identificadores G-, GT- y AW-.</span></label>
    <label className="flex flex-col gap-2 text-sm font-semibold">Clientify Site ID <span className="font-normal text-white/35">(opcional)</span><input value={settings.clientifySiteId} onChange={(e) => setSettings({ ...settings, clientifySiteId: e.target.value })} className={fieldClass} placeholder="Identificador de seguimiento" /></label>
    <button disabled={saving} className="inline-flex w-fit items-center rounded-full bg-brand px-6 py-3 text-sm font-bold text-ink disabled:opacity-50"><Save className="mr-2 size-4" />{saving ? 'Guardando...' : 'Guardar configuración'}</button>
  </section><aside className="flex flex-col gap-4"><div className="rounded-3xl border border-brand/20 bg-brand/10 p-6"><BarChart3 className="mb-4 size-6 text-brand" /><h3 className="font-bold">Medición centralizada</h3><p className="mt-2 text-sm leading-relaxed text-white/60">Los identificadores se cargan desde el servidor y no quedan escritos directamente en el código fuente.</p></div><div className="rounded-3xl border border-white/10 bg-ink-800 p-6"><ShieldCheck className="mb-4 size-6 text-brand" /><h3 className="font-bold">Consentimiento</h3><p className="mt-2 text-sm leading-relaxed text-white/50">Los píxeles respetan el sistema de consentimiento de cookies existente.</p><div className="mt-4 flex items-center gap-2 text-xs text-emerald-300"><CheckCircle2 className="size-4" />Protección activa</div></div></aside></form>
}
